imports:
    - { resource: parameters.yml }

framework:
    esi:             { enabled: true }
    #translator:      { fallback: %locale% }
    # The secret parameter is used to generate CSRF tokens
    secret:          058e7bdb3356d1e126041796db3b7371
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: false
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    session:
        name: "eZSESSID"
# Use the following line to get session name per siteaccess
#        name: "eZSESSID{siteaccess_hash}"

ez_publish_legacy:
    enabled: true
    root_dir: %kernel.root_dir%/ezpublish_legacy

parameters:
