parameters:
    ezpublish.api.storage_engine.default: legacy
    ezpublish.api.storage_engine.legacy.dsn: mysql://root@localhost/ezdemo
    ezpublish.siteaccess.default: ezdemo_site
    ezpublish.siteaccess.match_config:
        Map\URI:
            ezdemo_site: ezdemo_site
            ezdemo_site_admin: ezdemo_site_admin
        Map\Host:
            ezpublish.dev: ezdemo_site
            admin.ezpublish.dev: ezdemo_site_admin
    ezpublish.siteaccess.config.ezdemo_site_admin:
        useUrlAliasRouter: false
    #ezpublish.controller.content.view.options: {viewCache: false}
    ezpublish_legacy.view.default_layout: eZDemoBundle::pagelayout.html.twig
    ezpublish_legacy.view.content_block_name: content